baseurl = "https://nishasinha.github.io"
title = "Nisha Kumari"
theme = "LoveIt"
languageCode = "en-us"
paginate = 5000 #frontpage pagination

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  header_image = "images/main_go_wideandtall_darklayer.jpeg"
  title = "Software Engineering"
  slogan = "$ grep -rni \"The how's and why's\" ."
  SEOTitle = "Nisha Sinha Blog"
  keyword = "Software Engineer, Data Engineer, Devops, Cloud Computing, Hadoop"

  # Sidebar settings
  sidebar_about_description = "She/ Her, Senior Software Engineer, Interested in Distributed Systems, Data Engineering and Devops"
  sidebar_avatar = "images/nisha.jpeg"
  about_me = true

  featured_tags = true
  featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

  image_404 = "images/404-bg.jpg"
  title_404 = "We couldn't find what you were looking for..."

  omit_categories = false

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

  [params.social]
  rss            = true
  email          = "nishasinha68@gmail.com"
  linkedin       = "kumari-nisha"
  github         = "nishasinha"
  medium         = "@nishasinha"
  stackoverflow  = "7261783/nisha-sinha"

  [params.header]
      [params.header.title]
        # URL of the LOGO
        # LOGO 的 URL
        name = "Jhunak"